web:
  restart: always
  build: .
  container_name: awesome-vote
  command: npm start
  links:
   - db
  ports:
   - "3000:3000"
   - "5858:5858"
   - "35729:35729"
   - "80:80"
  environment:
   - NODE_ENV=production
  volumes:
   - ./:/opt/awesome-vote
   - /opt/awesome-vote/node_modules
   - /opt/awesome-vote/public
   - /opt/awesome-vote/uploads
db:
  image: mongo:3.2
  container_name: db_1
  restart: always
  ports:
   - "27017:27017"
  volumes:
   - db:/data/db
